# @see https://devdocs.prestashop.com/1.7/modules/concepts/controllers/admin-controllers/#how-to-map-an-action-of-your-controller-to-a-uri
# @see https://devdocs.prestashop.com/1.7/modules/concepts/controllers/admin-controllers/tabs/
#
# configuration
flavioski_modularsofas_configuration_index:
  path: /modularsofas/configuration
  methods: [GET]
  defaults:
    _controller: 'Flavioski\Module\ModularSofas\Controller\Admin\ConfigurationController::indexAction'
    _legacy_controller: 'AdminModularSofasConfiguration'
    _legacy_link: 'AdminModularSofasConfiguration'

# modular
flavioski_modularsofas_modular_index:
  path: /modularsofas/modular/{offset}/{limit}/{orderBy}/{sortOrder}
  methods: [GET]
  defaults:
    _controller: 'Flavioski\Module\ModularSofas\Controller\Admin\ModularController::indexAction'
    _legacy_controller: 'AdminModularSofasModular'
    _legacy_link: 'AdminModularSofasModular'
    limit: last
    offset: 0
    orderBy: last
    sortOrder: last
  requirements:
    limit: _limit|last|\d+
    orderBy: last|id_modular|name|code|active
    offset: last|\d+
    sortOrder: last|asc|desc

flavioski_modularsofas_modular_generate:
  path: /modularsofas/modular/generate
  methods: [GET, POST]
  defaults:
    _controller: 'Flavioski\Module\ModularSofas\Controller\Admin\ModularController::generateAction'
    _legacy_controller: 'AdminModularSofasModular'
    _legacy_link: 'AdminModularSofasModular:generate'

flavioski_modularsofas_modular_create:
  path: /modularsofas/modular/new
  methods: [GET, POST]
  defaults:
    _controller: 'Flavioski\Module\ModularSofas\Controller\Admin\ModularController::createAction'
    _legacy_controller: 'AdminModularSofasModular'
    _legacy_link: 'AdminModularSofasModular:add'

flavioski_modularsofas_modular_edit:
  path: /modularsofas/modular/{modularId}/edit
  methods: [GET, POST]
  defaults:
    _controller: 'Flavioski\Module\ModularSofas\Controller\Admin\ModularController::editAction'
    _legacy_controller: 'AdminModularSofasModular'
    _legacy_link: 'AdminModularSofasModular:update'
  requirements:
    modularId: \d+

flavioski_modularsofas_modular_delete:
  path: /modularsofas/modular/{modularId}/delete
  methods: [DELETE]
  defaults:
    _controller: 'Flavioski\Module\ModularSofas\Controller\Admin\ModularController::deleteAction'
    _legacy_controller: 'AdminModularSofasModular'
    _legacy_link: 'AdminModularSofasModular:deletemodular'
  requirements:
    modularId: \d+

flavioski_modularsofas_modular_bulk_delete:
  path: /modularsofas/modular/bulkDelete
  methods: [POST]
  defaults:
    _controller: 'Flavioski\Module\ModularSofas\Controller\Admin\ModularController::deleteBulkAction'
    _legacy_controller: 'AdminModularSofasModular'
    _legacy_link: 'AdminModularSofasModular:submitBulkdeletemodular'

flavioski_modularsofas_modular_toggle_status:
  path: /modularsofas/modular/{modularId}/toggle-status
  methods: [POST]
  defaults:
    _controller: 'Flavioski\Module\ModularSofas\Controller\Admin\ModularController::toggleStatusAction'
    _legacy_controller: 'AdminModularSofasModular'
    _legacy_link: 'AdminModularSofasModular:statusmodular'
    _legacy_parameters:
      id_modular: modularId
  requirements:
    modularId: \d+
