# @see https://devdocs.prestashop.com/1.7/modules/concepts/controllers/admin-controllers/#how-to-map-an-action-of-your-controller-to-a-uri
# @see https://devdocs.prestashop.com/1.7/modules/concepts/controllers/admin-controllers/tabs/
#
# configuration
flavioski_modularsofas_configuration_index:
  path: /modularsofas/configuration
  methods: [GET]
  defaults:
    _controller: 'Flavioski\Module\ModularSofas\Controller\Admin\ConfigurationController::indexAction'
    _legacy_controller: 'AdminModularSofasConfiguration'
    _legacy_link: 'AdminModularSofasConfiguration'

# modular
flavioski_modularsofas_modular_index:
  path: /modularsofas/modular/{offset}/{limit}/{orderBy}/{sortOrder}
  methods: [GET]
  defaults:
    _controller: 'Flavioski\Module\ModularSofas\Controller\Admin\ModularController::indexAction'
    _legacy_controller: 'AdminModularSofasModular'
    _legacy_link: 'AdminModularSofasModular'
    limit: last
    offset: 0
    orderBy: last
    sortOrder: last
  requirements:
    limit: _limit|last|\d+
    orderBy: last|id_modular|name|code|active
    offset: last|\d+
    sortOrder: last|asc|desc

flavioski_modularsofas_modular_generate:
  path: /modularsofas/modular/generate
  methods: [GET, POST]
  defaults:
    _controller: 'Flavioski\Module\ModularSofas\Controller\Admin\ModularController::generateAction'
    _legacy_controller: 'AdminModularSofasModular'
    _legacy_link: 'AdminModularSofasModular:generate'
